export const PRODUCT_CATALOG_VERSION = "template-2026-10-08";
export const PRODUCT_CATALOG = [
  {
    "id": "catalog-001",
    "category": "相机",
    "series": "Mini",
    "model": "Mini9",
    "spec": "蓝色",
    "officialPrice": 499,
    "capacity": 1,
    "image": "catalog/catalog-001.png",
    "createdAt": "catalog-2026-09-20-row-0002"
  },
  {
    "id": "catalog-002",
    "category": "相机",
    "series": "Mini",
    "model": "Mini12",
    "spec": "粉色",
    "officialPrice": 659,
    "capacity": 1,
    "image": "catalog/catalog-002.png",
    "createdAt": "catalog-2026-09-20-row-0003"
  },
  {
    "id": "catalog-003",
    "category": "相机",
    "series": "Mini",
    "model": "Mini12",
    "spec": "蓝色",
    "officialPrice": 659,
    "capacity": 1,
    "image": "catalog/catalog-003.png",
    "createdAt": "catalog-2026-09-20-row-0004"
  },
  {
    "id": "catalog-004",
    "category": "相机",
    "series": "Mini",
    "model": "Mini12",
    "spec": "紫色",
    "officialPrice": 659,
    "capacity": 1,
    "image": "catalog/catalog-004.png",
    "createdAt": "catalog-2026-09-20-row-0005"
  },
  {
    "id": "catalog-005",
    "category": "相机",
    "series": "Mini",
    "model": "Mini13",
    "spec": "粉色",
    "officialPrice": 659,
    "capacity": 1,
    "image": "catalog/catalog-005.png",
    "createdAt": "catalog-2026-09-20-row-0006"
  },
  {
    "id": "catalog-006",
    "category": "相机",
    "series": "SQ",
    "model": "SQ1",
    "spec": "白色",
    "officialPrice": 988,
    "capacity": 1,
    "image": "catalog/catalog-006.png",
    "createdAt": "catalog-2026-09-20-row-0007"
  },
  {
    "id": "catalog-007",
    "category": "相机",
    "series": "SQ",
    "model": "SQ1",
    "spec": "蓝色",
    "officialPrice": 988,
    "capacity": 1,
    "image": "catalog/catalog-007.png",
    "createdAt": "catalog-2026-09-20-row-0008"
  },
  {
    "id": "catalog-008",
    "category": "相机",
    "series": "SQ",
    "model": "SQ1",
    "spec": "橙色",
    "officialPrice": 988,
    "capacity": 1,
    "image": "catalog/catalog-008.png",
    "createdAt": "catalog-2026-09-20-row-0009"
  },
  {
    "id": "catalog-009",
    "category": "相机",
    "series": "SQ",
    "model": "SQ6",
    "spec": "泰勒联名",
    "officialPrice": 1888,
    "capacity": 1,
    "image": "catalog/catalog-009.png",
    "createdAt": "catalog-2026-09-20-row-0010"
  },
  {
    "id": "catalog-010",
    "category": "相机",
    "series": "Wide",
    "model": "Wide400",
    "spec": "绿色",
    "officialPrice": 1399,
    "capacity": 1,
    "image": "catalog/catalog-010.png",
    "createdAt": "catalog-2026-09-20-row-0011"
  },
  {
    "id": "catalog-011",
    "category": "相纸",
    "series": "Mini",
    "model": "白边",
    "spec": "单白",
    "officialPrice": 43,
    "capacity": 10,
    "image": "catalog/catalog-011.png",
    "createdAt": "catalog-2026-09-20-row-0012"
  },
  {
    "id": "catalog-012",
    "category": "相纸",
    "series": "Mini",
    "model": "白边",
    "spec": "双白",
    "officialPrice": 79,
    "capacity": 20,
    "image": "catalog/catalog-012.png",
    "createdAt": "catalog-2026-09-20-row-0013"
  },
  {
    "id": "catalog-013",
    "category": "相纸",
    "series": "Mini",
    "model": "手绘kitty",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-013.png",
    "createdAt": "catalog-2026-09-20-row-0014"
  },
  {
    "id": "catalog-014",
    "category": "相纸",
    "series": "Mini",
    "model": "双子星",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-014.png",
    "createdAt": "catalog-2026-09-20-row-0015"
  },
  {
    "id": "catalog-015",
    "category": "相纸",
    "series": "Mini",
    "model": "石灰岩",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-015.png",
    "createdAt": "catalog-2026-09-20-row-0016"
  },
  {
    "id": "catalog-016",
    "category": "相纸",
    "series": "Mini",
    "model": "涂鸦",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-016.png",
    "createdAt": "catalog-2026-09-20-row-0017"
  },
  {
    "id": "catalog-017",
    "category": "相纸",
    "series": "Mini",
    "model": "花雨",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-017.png",
    "createdAt": "catalog-2026-09-20-row-0018"
  },
  {
    "id": "catalog-018",
    "category": "相纸",
    "series": "Mini",
    "model": "人鱼",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-018.png",
    "createdAt": "catalog-2026-09-20-row-0019"
  },
  {
    "id": "catalog-019",
    "category": "相纸",
    "series": "Mini",
    "model": "黑白",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-019.png",
    "createdAt": "catalog-2026-09-20-row-0020"
  },
  {
    "id": "catalog-020",
    "category": "相纸",
    "series": "Mini",
    "model": "黑边",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-020.png",
    "createdAt": "catalog-2026-09-20-row-0021"
  },
  {
    "id": "catalog-021",
    "category": "相纸",
    "series": "Mini",
    "model": "爱心",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-021.png",
    "createdAt": "catalog-2026-09-20-row-0022"
  },
  {
    "id": "catalog-022",
    "category": "相纸",
    "series": "Mini",
    "model": "糖霜",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-022.png",
    "createdAt": "catalog-2026-09-20-row-0023"
  },
  {
    "id": "catalog-023",
    "category": "相纸",
    "series": "Mini",
    "model": "天青石",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-023.png",
    "createdAt": "catalog-2026-09-20-row-0024"
  },
  {
    "id": "catalog-024",
    "category": "相纸",
    "series": "Mini",
    "model": "紫边",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-024.png",
    "createdAt": "catalog-2026-09-20-row-0025"
  },
  {
    "id": "catalog-025",
    "category": "相纸",
    "series": "Mini",
    "model": "蓝边",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-025.png",
    "createdAt": "catalog-2026-09-20-row-0026"
  },
  {
    "id": "catalog-026",
    "category": "相纸",
    "series": "Mini",
    "model": "粉边",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-026.png",
    "createdAt": "catalog-2026-09-20-row-0027"
  },
  {
    "id": "catalog-027",
    "category": "相纸",
    "series": "Mini",
    "model": "马卡龙",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-027.png",
    "createdAt": "catalog-2026-09-20-row-0028"
  },
  {
    "id": "catalog-028",
    "category": "相纸",
    "series": "Mini",
    "model": "彩虹",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-028.png",
    "createdAt": "catalog-2026-09-20-row-0029"
  },
  {
    "id": "catalog-029",
    "category": "相纸",
    "series": "Mini",
    "model": "花花调色盘",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-029.png",
    "createdAt": "catalog-2026-09-20-row-0030"
  },
  {
    "id": "catalog-030",
    "category": "相纸",
    "series": "Mini",
    "model": "米奇",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-030.png",
    "createdAt": "catalog-2026-09-20-row-0031"
  },
  {
    "id": "catalog-031",
    "category": "相纸",
    "series": "Mini",
    "model": "维尼",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-031.png",
    "createdAt": "catalog-2026-09-20-row-0032"
  },
  {
    "id": "catalog-032",
    "category": "相纸",
    "series": "Mini",
    "model": "黑胶",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-032.png",
    "createdAt": "catalog-2026-09-20-row-0033"
  },
  {
    "id": "catalog-033",
    "category": "相纸",
    "series": "Mini",
    "model": "流光",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-033.png",
    "createdAt": "catalog-2026-09-20-row-0034"
  },
  {
    "id": "catalog-034",
    "category": "相纸",
    "series": "Mini",
    "model": "浮光",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-034.png",
    "createdAt": "catalog-2026-09-20-row-0035"
  },
  {
    "id": "catalog-035",
    "category": "相纸",
    "series": "Mini",
    "model": "银河",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-035.png",
    "createdAt": "catalog-2026-09-20-row-0036"
  },
  {
    "id": "catalog-036",
    "category": "相纸",
    "series": "Mini",
    "model": "波点",
    "spec": "",
    "officialPrice": 61,
    "capacity": 10,
    "image": "catalog/catalog-036.png",
    "createdAt": "catalog-2026-09-20-row-0037"
  },
  {
    "id": "catalog-037",
    "category": "相纸",
    "series": "SQ",
    "model": "白边",
    "spec": "单白",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-037.png",
    "createdAt": "catalog-2026-09-20-row-0038"
  },
  {
    "id": "catalog-038",
    "category": "相纸",
    "series": "SQ",
    "model": "白边",
    "spec": "双白",
    "officialPrice": 119,
    "capacity": 20,
    "image": "catalog/catalog-038.png",
    "createdAt": "catalog-2026-09-20-row-0039"
  },
  {
    "id": "catalog-039",
    "category": "相纸",
    "series": "SQ",
    "model": "黑边",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-039.png",
    "createdAt": "catalog-2026-09-20-row-0040"
  },
  {
    "id": "catalog-040",
    "category": "相纸",
    "series": "SQ",
    "model": "星空",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-040.png",
    "createdAt": "catalog-2026-09-20-row-0041"
  },
  {
    "id": "catalog-041",
    "category": "相纸",
    "series": "SQ",
    "model": "日落",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-041.png",
    "createdAt": "catalog-2026-09-20-row-0042"
  },
  {
    "id": "catalog-042",
    "category": "相纸",
    "series": "SQ",
    "model": "彩虹",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-042.png",
    "createdAt": "catalog-2026-09-20-row-0043"
  },
  {
    "id": "catalog-043",
    "category": "相纸",
    "series": "SQ",
    "model": "黑白",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-043.png",
    "createdAt": "catalog-2026-09-20-row-0044"
  },
  {
    "id": "catalog-044",
    "category": "相纸",
    "series": "SQ",
    "model": "汉白玉",
    "spec": "",
    "officialPrice": 69,
    "capacity": 10,
    "image": "catalog/catalog-044.png",
    "createdAt": "catalog-2026-09-20-row-0045"
  },
  {
    "id": "catalog-045",
    "category": "相纸",
    "series": "SQ",
    "model": "泰勒联名",
    "spec": "",
    "officialPrice": 130,
    "capacity": 10,
    "image": "catalog/catalog-045.png",
    "createdAt": "catalog-2026-09-20-row-0046"
  },
  {
    "id": "catalog-046",
    "category": "相纸",
    "series": "Wide",
    "model": "白边",
    "spec": "单白",
    "officialPrice": 79,
    "capacity": 10,
    "image": "catalog/catalog-046.png",
    "createdAt": "catalog-2026-09-20-row-0047"
  },
  {
    "id": "catalog-047",
    "category": "相纸",
    "series": "Wide",
    "model": "白边",
    "spec": "双白",
    "officialPrice": 129,
    "capacity": 20,
    "image": "catalog/catalog-047.png",
    "createdAt": "catalog-2026-09-20-row-0048"
  },
  {
    "id": "catalog-048",
    "category": "相纸",
    "series": "Wide",
    "model": "彩虹",
    "spec": "",
    "officialPrice": 139,
    "capacity": 20,
    "image": "catalog/catalog-048.png",
    "createdAt": "catalog-2026-09-20-row-0049"
  },
  {
    "id": "catalog-049",
    "category": "相纸",
    "series": "Wide",
    "model": "黑边",
    "spec": "",
    "officialPrice": 89,
    "capacity": 10,
    "image": "catalog/catalog-049.png",
    "createdAt": "catalog-2026-09-20-row-0050"
  },
  {
    "id": "catalog-050",
    "category": "相纸",
    "series": "Wide",
    "model": "鎏金",
    "spec": "",
    "officialPrice": 89,
    "capacity": 10,
    "image": "catalog/catalog-050.png",
    "createdAt": "catalog-2026-09-20-row-0051"
  },
  {
    "id": "catalog-051",
    "category": "相纸",
    "series": "Wide",
    "model": "黑白",
    "spec": "",
    "officialPrice": 87,
    "capacity": 10,
    "image": "catalog/catalog-051.png",
    "createdAt": "catalog-2026-09-20-row-0052"
  }
];
